### ISSUE TITLE
Cannot run command "yarn ios"

### ISSUE THREAD

**Issue by baonguyenhsts** [saigon-technology/rn-base-project-typescript#216]
<img width="682" alt="Screenshot 2024-04-09 at 11 18 36 AM" src="https://github.com/saigontechnology/rn-base-project-typescript/assets/62632321/ac67c5d1-2efd-4e2e-b3c3-330f2f737408">

**Comment by huydosgtech** [comment]
@baonguyenhsts we need install **ios-deploy** then can connect with device
https://stackoverflow.com/questions/38495793/run-react-native-application-on-ios-device-directly-from-command-line

All my side I can yarn ios success. 

<img width="1065" alt="Screenshot 2024-04-21 at 9 39 19 PM" src="https://github.com/saigontechnology/rn-base-project-typescript/assets/105196859/814bef60-7a7b-4e32-9612-b398db9405e6">




If you still failed please try these steps below

- delete Podfile.lock
- yarn
- cd iOS & pod install
- yarn iOS

**Comment by baonguyenhsts** [comment]
I believe we don't need to install `ios-deploy` to run the command, as my previous projects haven't required it. Additionally, the weekly download rate of `ios-deploy` is not high enough to warrant its installation.

**Comment by huydosgtech** [comment]
@baonguyenhsts after uninstalled **`ios-deploy`** my side, It still working when run yarn ios. Could you check it again? Thank you

**Comment by huydosgtech** [comment]
I encountered this issue after running my app on both actual physical device and simulator. So I go to Xcode > Device and simulator > unpair real device. And then it's working

<img width="1173" alt="Screenshot 2024-05-22 at 4 39 15 PM" src="https://github.com/saigontechnology/rn-base-project-typescript/assets/105196859/261f8fa7-d25c-4c49-b9b1-7368d966dcdd">

For information to resolve this problem at here: 
https://github.com/facebook/react-native/issues/35917#issuecomment-1871081177
